[project]
name = "fakezel"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "discord-py[voice]>=2.6.3",
    "gtts>=2.5.4",
    "piper-tts==1.2.0",
]
